#host
https://discovery.meethue.com

#curl options
 --silent
# include response headers
# --include
# to ignore SSL when working with localhost
# --insecure
# to read a header(s) from a file.  File format should be like:
# Header-Name: Header-Value
# e.g. Authorization: YOUR_AUTH_TOKEN_HERE
# -H @/path/to/file.txt

# headers
# Accept: application/json;
# Connection: keep-alive
# Content-Type: application/json; charset=utf-8
# User-Agent: VRC

# query
GET /

# body
# {
#   "test": 123
# }

#############

https://192.168.1.219
--silent
--insecure
Content-Type: application/json
GET /api

https://192.168.1.219
--silent
--insecure
Content-Type: application/json
POST /api
{"devicetype":"testingKue", "generateclientkey":true}

#############

https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
GET /clip/v2/resource/scene

#############

https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
GET /clip/v2/resource/scene/6223bf09-c195-477f-939d-543f9d3d2204

#############

# scene glue
https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
PUT /clip/v2/resource/scene/6223bf09-c195-477f-939d-543f9d3d2204

{"recall":{"action": "active"}}
# Scene read
https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
PUT /clip/v2/resource/scene/decbe834-f752-46e1-a18f-2c6fc87e063b

{"recall":{"action": "active"}}

#############

https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
GET /clip/v2/resource/zone

#############

https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
GET /clip/v2/resource/grouped_light/3a3e2753-d496-433e-84b6-15134d520666

#############

https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
PUT /clip/v2/resource/grouped_light/3a3e2753-d496-433e-84b6-15134d520666
{
    "on": {
        "on": false
    } 
}

#############

https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
GET /clip/v2/resource/room/9acaaa4a-767d-4171-990d-7cfe7749d589

#############

https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
GET /clip/v2/resource/light
#table lighstrip light: ee771934-4c64-47d7-9e2c-d9e4ecdd9d3c

#############

https://192.168.1.219
--silent
--insecure
hue-application-key: 1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3
Content-Type: application/json
GET /clip/v2/resource/device/ff479675-4915-4692-8b85-f33717dece9d

#############

https://192.168.1.219:443
--silent
--insecure
POST /api
{
    "devicetype":"app_name#instance_name",
    "generateclientkey":true
}

#############
# [
#     {
#         "success": {
#             "username": "1zUztGOp6k4Z7K1Krz2RJHlbHEpMYkcjTbmfdrL3",
#             "clientkey": "83C7945586C79469A24C8B10492D71F6"
#         }
#     }
# ]
